export const SAVE_WORKFLOW_REQUEST = "SAVE_WORKFLOW_REQUEST";
export const SAVE_WORKFLOW_SUCCESS = "SAVE_WORKFLOW_SUCCESS";
export const SAVE_WORKFLOW_FAIL = "SAVE_WORKFLOW_FAIL";

export const FETCH_WORKFLOW_REQUEST = "FETCH_WORKFLOW_REQUEST";
export const FETCH_WORKFLOW_SUCCESS = "FETCH_WORKFLOW_SUCCESS";
export const FETCH_WORKFLOW_FAIL = "FETCH_WORKFLOW_FAIL";

export const RUN_WORKFLOW_REQUEST = "RUN_WORKFLOW_REQUEST";
export const RUN_WORKFLOW_SUCCESS = "RUN_WORKFLOW_SUCCESS";
export const RUN_WORKFLOW_FAIL = "RUN_WORKFLOW_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";